### ISSUE TITLE
Startseite designen (Struktur)

### ISSUE THREAD

**Issue by johan-stph** [kit-recipe-app/recipe-app#11]
Auswahl treffen, über Inhalt der Startseite; Design und Struktur des angezeigten Inhalts
Bestandteile, die nicht dazu gehören: Navigation Bar, Header

**Comment by StefanLoeffelholz** [comment]
![Image](https://user-images.githubusercontent.com/117743469/205299261-ac9b3425-36ab-4299-9061-2ee9b797c7ee.png)
