### ISSUE TITLE
App-Design-Entwurf

### ISSUE THREAD

**Issue by yalllah** [kit-recipe-app/recipe-app#9]
- [ ] 1. Theme-Colour festlegen
- [ ] 2. Startseite festlegen und designen
- [ ] 3. Menüleiste
- [ ] 4. Einkaufsliste (a. Übersicht der einzelnen Listen, b. Einkaufsliste selbst)
- [ ] 5. Rezepte (a. Übersicht (i. Vorschläge), b. Rezept, c. Rezept erstellen (i. Erstellungsformular))
- [ ] 6. Profil (a. Übersicht, b. Einstellungen, c. Freunde)

**Comment by johan-stph** [comment]
This Issue was separated into smaller issues.
